#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Mar 31 01:18:43 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=photon-main.zip
