#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Mar 11 03:36:54 CET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Solas Shader V3.4.zip
